WITH cleaned AS (
    SELECT 
        TRANSACTION_ID,
        CAST(PAYMENT_AMOUNT AS DECIMAL(10,2)) AS PAYMENT_AMOUNT,
        CAST(REFUND_AMOUNT AS DECIMAL(10,2)) AS REFUND_AMOUNT,
        LOWER(PAYMENT_STATUS) AS PAYMENT_STATUS,
        LOWER(PAYMENT_METHOD) AS PAYMENT_METHOD
    FROM {{ ref('stg_payments') }}
)
SELECT * FROM cleaned