WITH cleaned AS (
    SELECT 
        CUSTOMER_ID,
        INITCAP(CUSTOMER_NAME) AS CUSTOMER_NAME,
        CUSTOMER_AGE,
        UPPER(CUSTOMER_GENDER) AS CUSTOMER_GENDER,
        LOWER(CUSTOMER_EMAIL) AS CUSTOMER_EMAIL,
        REGEXP_REPLACE(CUSTOMER_PHONE, '[^0-9]', '') AS CUSTOMER_PHONE,
        CUSTOMER_TYPE,
        CUSTOMER_SEGMENT
    FROM {{ ref('stg_customers') }}
)
SELECT * FROM cleaned