WITH yearly_revenue AS (
    SELECT 
        YEAR(SERVICE_DATE) AS YEAR,
        SUM(PAYMENT_AMOUNT) AS TOTAL_REVENUE,
        COUNT(TRANSACTION_ID) AS TOTAL_TRANSACTIONS,
        AVG(PAYMENT_AMOUNT) AS AVG_TRANSACTION_VALUE
    FROM {{ ref('core_fact_transactions') }}
    GROUP BY YEAR(SERVICE_DATE)
),
growth AS (
    SELECT 
        YEAR,
        TOTAL_REVENUE,
        LAG(TOTAL_REVENUE) OVER (ORDER BY YEAR) AS PREV_YEAR_REVENUE,
        ROUND((TOTAL_REVENUE - LAG(TOTAL_REVENUE) OVER (ORDER BY YEAR)) / LAG(TOTAL_REVENUE) OVER (ORDER BY YEAR) * 100, 2) AS YOY_GROWTH
    FROM yearly_revenue
)
SELECT * FROM growth