SELECT 
    SERVICE_TYPE,
    SUM(TOTAL_TRANSACTIONS) AS TOTAL_TRANSACTIONS,
    SUM(TOTAL_REVENUE) AS TOTAL_REVENUE,
    AVG(AVG_TRANSACTION_VALUE) AS AVG_TRANSACTION_VALUE
FROM {{ ref('mart_service_type_performance') }}
GROUP BY SERVICE_TYPE
ORDER BY TOTAL_REVENUE DESC