SELECT 
    CUSTOMER_SEGMENT,
    COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_CUSTOMERS,
    SUM(TOTAL_SPENT) AS TOTAL_REVENUE,
    AVG(TOTAL_SPENT) AS AVG_SPEND_PER_CUSTOMER,
    COUNT(*) AS TOTAL_TRANSACTIONS
FROM {{ ref('mart_customer_lifetime_value') }}
GROUP BY CUSTOMER_SEGMENT
ORDER BY TOTAL_REVENUE DESC