WITH service_usage AS (
    SELECT 
        CUSTOMER_ID,
        SERVICE_TYPE,
        COUNT(TRANSACTION_ID) AS USAGE_FREQUENCY,
        SUM(PAYMENT_AMOUNT) AS TOTAL_SPEND
    FROM {{ ref('core_fact_transactions') }}
    GROUP BY CUSTOMER_ID, SERVICE_TYPE
)
SELECT 
    SERVICE_TYPE,
    COUNT(DISTINCT CUSTOMER_ID) AS UNIQUE_CUSTOMERS,
    AVG(USAGE_FREQUENCY) AS AVG_USAGE_PER_CUSTOMER,
    SUM(TOTAL_SPEND) AS TOTAL_REVENUE
FROM service_usage
GROUP BY SERVICE_TYPE
ORDER BY AVG_USAGE_PER_CUSTOMER DESC